"""crear esquema inicial

Revision ID: 8c88fdd3db71
Revises: 
Create Date: 2026-06-28 22:25:23.876451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c88fdd3db71'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dispositivos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=60), nullable=False),
    sa.Column('potencia_base', sa.Float(), nullable=False, comment='Watts nominales'),
    sa.Column('limite_seguro', sa.Float(), nullable=False, comment='Umbral de sobrecarga en W'),
    sa.Column('activo', sa.SmallInteger(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre'),
    comment='Catálogo de dispositivos eléctricos'
    )
    op.create_table('reportes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fecha_generacion', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('periodo_inicio', sa.DateTime(), nullable=False),
    sa.Column('periodo_fin', sa.DateTime(), nullable=False),
    sa.Column('total_lecturas', sa.Integer(), nullable=False),
    sa.Column('total_energia_kwh', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('total_costo_cop', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('proyeccion_mensual', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('total_sobrecargas', sa.Integer(), nullable=False),
    sa.Column('dispositivo_top', sa.String(length=60), nullable=True, comment='Mayor consumidor'),
    sa.Column('datos_json', sa.JSON(), nullable=True, comment='Reporte completo serializado'),
    sa.PrimaryKeyConstraint('id'),
    comment='Reportes generados por el motor de análisis'
    )
    with op.batch_alter_table('reportes', schema=None) as batch_op:
        batch_op.create_index('idx_reportes_fecha', ['fecha_generacion'], unique=False)

    op.create_table('alertas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dispositivo_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('PICO', 'SOSTENIDA', 'ADVERTENCIA'), nullable=False),
    sa.Column('potencia_pico', sa.Float(), nullable=False, comment='Peor W registrado en el evento'),
    sa.Column('duracion_min', sa.Integer(), nullable=False, comment='Minutos en sobrecarga'),
    sa.Column('timestamp_inicio', sa.DateTime(), nullable=False),
    sa.Column('timestamp_fin', sa.DateTime(), nullable=False),
    sa.Column('resuelta', sa.SmallInteger(), nullable=False, server_default='0'),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dispositivo_id'], ['dispositivos.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    comment='Eventos de sobrecarga y advertencia detectados'
    )
    with op.batch_alter_table('alertas', schema=None) as batch_op:
        batch_op.create_index('idx_alertas_disp', ['dispositivo_id'], unique=False)
        batch_op.create_index('idx_alertas_resuelta', ['resuelta'], unique=False)
        batch_op.create_index('idx_alertas_tipo', ['tipo'], unique=False)

    op.create_table('costos_diarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dispositivo_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('energia_kwh', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('costo_cop', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('franja_valle', sa.Numeric(precision=14, scale=2), nullable=False, comment='Costo 00-06h'),
    sa.Column('franja_normal', sa.Numeric(precision=14, scale=2), nullable=False, comment='Costo 06-18h'),
    sa.Column('franja_punta', sa.Numeric(precision=14, scale=2), nullable=False, comment='Costo 18-24h'),
    sa.ForeignKeyConstraint(['dispositivo_id'], ['dispositivos.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dispositivo_id', 'fecha', name='uq_disp_fecha'),
    comment='Costos energéticos agregados por día'
    )
    with op.batch_alter_table('costos_diarios', schema=None) as batch_op:
        batch_op.create_index('idx_costos_fecha', ['fecha'], unique=False)

    op.create_table('lecturas',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('dispositivo_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('potencia_w', sa.Float(), nullable=False, comment='Watts en este instante'),
    sa.Column('energia_kwh', sa.Numeric(precision=10, scale=6), nullable=False, comment='kWh consumidos en el intervalo'),
    sa.Column('costo_cop', sa.Numeric(precision=12, scale=4), nullable=False, comment='Costo en pesos colombianos'),
    sa.Column('es_sobrecarga', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['dispositivo_id'], ['dispositivos.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    comment='Lecturas de consumo por intervalo de 15 minutos'
    )
    with op.batch_alter_table('lecturas', schema=None) as batch_op:
        batch_op.create_index('idx_disp_tiempo', ['dispositivo_id', 'timestamp'], unique=False)
        batch_op.create_index('idx_sobrecarga', ['es_sobrecarga'], unique=False)
        batch_op.create_index('idx_timestamp', ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lecturas', schema=None) as batch_op:
        batch_op.drop_index('idx_timestamp')
        batch_op.drop_index('idx_sobrecarga')
        batch_op.drop_index('idx_disp_tiempo')

    op.drop_table('lecturas')
    with op.batch_alter_table('costos_diarios', schema=None) as batch_op:
        batch_op.drop_index('idx_costos_fecha')

    op.drop_table('costos_diarios')
    with op.batch_alter_table('alertas', schema=None) as batch_op:
        batch_op.drop_index('idx_alertas_tipo')
        batch_op.drop_index('idx_alertas_resuelta')
        batch_op.drop_index('idx_alertas_disp')

    op.drop_table('alertas')
    with op.batch_alter_table('reportes', schema=None) as batch_op:
        batch_op.drop_index('idx_reportes_fecha')

    op.drop_table('reportes')
    op.drop_table('dispositivos')
    # ### end Alembic commands ###
